const APPLICATION_TITLE = 'Search for Sessions';
const SEARCH_BUTTON_LABEL = 'Search';
const RESET_BUTTON_LABEL = 'Reset';
const ADD_BUTTON_LABEL = 'Add';

export {
    APPLICATION_TITLE,
    SEARCH_BUTTON_LABEL,
    RESET_BUTTON_LABEL,
    ADD_BUTTON_LABEL
};
